
export const Routes = {
    // pages
    Presentation: { path: "/" },
    DashboardOverview: { path: "/dashboard/overview" },
    Transactions: { path: "/transactions" },
    Settings: { path: "/settings" },
    Upgrade: { path: "/upgrade" },
    BootstrapTables: { path: "/tables/bootstrap-tables" },
    Billing: { path: "/examples/billing" },
    Invoice: { path: "/examples/invoice" },
    Signin: { path: "/examples/sign-in" },
    Signup: { path: "/examples/sign-up" },
    ForgotPassword: { path: "/examples/forgot-password" },
    ResetPassword: { path: "/examples/reset/:token" },
    Lock: { path: "/examples/lock" },
    NotFound: { path: "/examples/404" },
    ServerError: { path: "/examples/500" },
    

    // docs
    DocsOverview: { path: "/documentation/overview" },
    DocsDownload: { path: "/documentation/download" },
    DocsQuickStart: { path: "/documentation/quick-start" },
    DocsLicense: { path: "/documentation/license" },
    DocsFolderStructure: { path: "/documentation/folder-structure" },
    DocsBuild: { path: "/documentation/build-tools" },
    DocsChangelog: { path: "/documentation/changelog" },

    // components
    Accordions: { path: "/components/accordions" },
    Alerts: { path: "/components/alerts" },
    Badges: { path: "/components/badges" },
    Widgets: { path: "/widgets" },
    Breadcrumbs: { path: "/components/breadcrumbs" },
    Buttons: { path: "/components/buttons" },
    Forms: { path: "/components/forms/:id" },
    Modals: { path: "/components/modals" },
    Navs: { path: "/components/navs" },
    Navbars: { path: "/components/navbars" },
    Pagination: { path: "/components/pagination" },
    Popovers: { path: "/components/popovers" },
    Progress: { path: "/components/progress" },
    Tables: { path: "/components/tables" },
    Tabs: { path: "/components/tabs/:id" },
    Tooltips: { path: "/components/tooltips" },
    Toasts: { path: "/components/toasts" },
    WidgetsComponent: { path: "/components/widgets" },
    Widget: { path: "/components/userdetail" },
    Fleetowner:{path:"/components/fleetowner"},
    Enrolledit:{path:"/components/enrolledit/:id"},
    Editenroll:{path:"/components/editenroll/:id"},
    Addpassenger:{path:"/components/addpassenger"},
    Viewpassenger:{path:"/components/viewpassenger"},
    Editpassenger:{path:"/components/editpassenger/:id"},
    Addcorporate:{path:"/components/addcorporate"},
    Viewcorporate:{path:"/components/viewcorporate"},
    Editcorporate:{path:"/components/editcorporate/:id"},
    Addvehicle:{path:"/components/addvehicle/:id"},
    Activetrips:{path:"/components/activetrips"},
    Completedtrips:{path:"/components/completedtrips"},
    Bookedtrips:{path:"/components/bookedtrips"},
    Cancelledtrips:{path:"/components/cancelledtrips"},
    Overall:{path:"/components/overall"},
    Providerstatement:{path:"/components/providerstatement"},
    Dailystatement:{path:"/components/dailystatement"},
    Monthlystatement:{path:"/components/monthlystatement"},
    yearlystatement:{path:"/components/yearlystatement"},
    Paymentsetting:{path:"/components/paymentsetting"},
    Paymenthistory:{path:"/components/paymenthistory"},
    Sitesetting:{path:"/components/sitesettings"},
    Translation:{path:"/components/translation"},
    Documentsrenewal:{path:"/components/documentsrenewal"},
    Terms:{path:"/components/terms"},
    Privacypolicy:{path:"/components/privacypolicy"},
    Aboutus:{path:"/components/aboutus"},
    Help:{path:"/components/help"},
    Faq:{path:"/components/faq"},
    Adminprofile:{path:"/components/adminprofile"},
    Changepassword:{path:"/components/changepassword"},
    Editdocumentrenewal:{path:"/components/editdocumentrenewal/:id"},
    Heatmap:{path:"/components/heatmap"},
    Map:{path:"/components/map"},
    Bookedrides:{path:"/components/bookedrides"},
    Completedrides:{path:"/components/completedrides"},
    Activerides:{path:"/components/activerides"},
    Cancelledrides:{path:"/components/cancelledrides"},
    Tripreports:{path:"/components/tripreports"},
    Driverview:{path:"/components/driverview"},
    Editdriver:{path:"/components/editdriverscheme/:id"},

};